version: "3.7"

services:
  pyth:
    build: ./py_exec
    container_name: python_container
    volumes:
      - ./py_exec/output:/output
    depends_on:
      - vpn
    network_mode: "service:vpn"
  vpn:
    build: ./vpn
    container_name: vpn_container
    restart: always
    devices:
      - /dev/ppp
    cap_add:
      - "NET_ADMIN"

